import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Navbar from '../Components/Navbar';
import Cards from '../Components/Cards';

export default function Home() {
  return (
    <>
         <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Prompt&display=swap" rel="stylesheet"/>
      </Head>
      <Navbar />
    <div>
 <main className={styles.main}>
        <div>
        <img className="bg-img" src="design3.webp" />
        <p className="welcome-note">Welcome to my portfolio website! My name is Hannan Shaukat, <br/> I'm a blockchain developer with expertise in building websites and Solidity contracts. <br/>I'm passionate about creating innovative solutions using blockchain technology, and <br/>I've worked on several projects that demonstrate my skills in this area. On this website, <br/>you'll find examples of my work, as well as information about my background and <br/>experience. I'm excited to share my portfolio with you and invite you to explore my projects.</p>
        </div>
      </main>
      <hr/>
      </div>

        <div>

        <Cards/>

      </div>
      
    
      </>

  )
}
